PROGRAM CALCULADORA
INTEGER OP, A, B, RESINT
REAL X, Y, RESREAL

PRINT *, 'SELECIONE OPERACAO (1-SOMA INTEIRA, 2-DIVISAO REAL):'
READ *, OP

IF (OP .EQ. 1) THEN
   A = 15
   B = 25
   RESINT = A + B
   PRINT *, 'RESULTADO DA SOMA INTEIRA: ', RESINT
ELSE
   IF (OP .EQ. 2) THEN
      X = 20.0
      Y = 4.0
      RESREAL = X / Y
      PRINT *, 'RESULTADO DA DIVISAO REAL: ', RESREAL
   ELSE
      PRINT *, 'OPERACAO INVALIDA SELECCIONADA'
   ENDIF
ENDIF
END